In [1]:
import torch

In [30]:
maskFFT = torch.arange(70).reshape(1,7,10)
print(f'maskFFT:\n{maskFFT}\n')
kernel = torch.arange(25).reshape(1, 5, 5)
knxh, knyh = kernel.shape[-2] // 2, kernel.shape[-1] // 2
print(f'knxh:{knxh}, knyh:{knyh}\n')
print(f'kernel:\n{kernel}\n')
kernelNum = 1
output = torch.zeros(kernelNum, a.shape[-2], a.shape[-1])
print(f'result:\n{output}')

maskFFT:
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]])

knxh:2, knyh:2

kernel:
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]]])

result:
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])


In [31]:
# top-left corner
output[:, :knxh+1, :knyh+1] = maskFFT[:, :knxh+1, :knyh+1] * kernel[:kernelNum, -(knxh+1):, -(knyh+1):]
print(f'Corresponding maskFFT region:\n{maskFFT[:, :knxh+1, :knyh+1]}\n')
print(f'Corresponding kernel region:\n{kernel[:kernelNum, -(knxh+1):, -(knyh+1):]}\n')
print(f'Result: {output}')

Corresponding maskFFT region:
tensor([[[ 0,  1,  2],
         [10, 11, 12],
         [20, 21, 22]]])

Corresponding kernel region:
tensor([[[12, 13, 14],
         [17, 18, 19],
         [22, 23, 24]]])

Result: tensor([[[  0.,  13.,  28.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [170., 198., 228.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [440., 483., 528.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]]])


In [32]:
# top right corner
output[:, :knxh+1, -knyh:] = maskFFT[:, :knxh+1, -knyh:] * kernel[:kernelNum, -(knxh+1):, :knyh]
print(f'Corresponding maskFFT region:\n{maskFFT[:, :knxh+1, -knyh:]}')
print(f'Corresponding kernel region:\n{kernel[:kernelNum, -(knxh+1):, :knyh]}')
print(f'Result:\n{output}')

Corresponding maskFFT region:
tensor([[[ 8,  9],
         [18, 19],
         [28, 29]]])
Corresponding kernel region:
tensor([[[10, 11],
         [15, 16],
         [20, 21]]])
Result:
tensor([[[  0.,  13.,  28.,   0.,   0.,   0.,   0.,   0.,  80.,  99.],
         [170., 198., 228.,   0.,   0.,   0.,   0.,   0., 270., 304.],
         [440., 483., 528.,   0.,   0.,   0.,   0.,   0., 560., 609.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]]])


In [33]:
# bottom-left quadrant
output[:, -knxh:, :knyh+1] = maskFFT[:, -knxh:, :knyh+1] * kernel[:kernelNum, :knxh, -(knyh+1):]
print(f'Corresponding maskFFT region:\n{maskFFT[:, -knxh:, :knyh+1]}')
print(f'Corresponding kernel region:\n{kernel[:kernelNum, :knxh, -(knyh+1):]}')
print(f'Result:\n{output}')

Corresponding maskFFT region:
tensor([[[50, 51, 52],
         [60, 61, 62]]])
Corresponding kernel region:
tensor([[[2, 3, 4],
         [7, 8, 9]]])
Result:
tensor([[[  0.,  13.,  28.,   0.,   0.,   0.,   0.,   0.,  80.,  99.],
         [170., 198., 228.,   0.,   0.,   0.,   0.,   0., 270., 304.],
         [440., 483., 528.,   0.,   0.,   0.,   0.,   0., 560., 609.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [100., 153., 208.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [420., 488., 558.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]]])


In [34]:
# bottom-right quadrant
output[:, -knxh:, -knyh:] = maskFFT[:, -knxh:, -knyh:] * kernel[:kernelNum, :knxh, :knyh]
print(f'Corresponding maskFFT region:\n{maskFFT[:, -knxh:, -knyh:]}')
print(f'Corresponding kernel region:\n{kernel[:kernelNum, :knxh, :knyh]}')
print(f'Result:\n{output}')

Corresponding maskFFT region:
tensor([[[58, 59],
         [68, 69]]])
Corresponding kernel region:
tensor([[[0, 1],
         [5, 6]]])
Result:
tensor([[[  0.,  13.,  28.,   0.,   0.,   0.,   0.,   0.,  80.,  99.],
         [170., 198., 228.,   0.,   0.,   0.,   0.,   0., 270., 304.],
         [440., 483., 528.,   0.,   0.,   0.,   0.,   0., 560., 609.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
         [100., 153., 208.,   0.,   0.,   0.,   0.,   0.,   0.,  59.],
         [420., 488., 558.,   0.,   0.,   0.,   0.,   0., 340., 414.]]])
